### ISSUE TITLE
Question about personalization rules for MACs calculation

### ISSUE THREAD

**Issue by Sebo-the-tramp** [microsoft/ORBIT-Dataset#11]
Thank you for providing the great dataset and project.

I'm just asking about the following snippet of the readme.Md file in the repo:

--- 

What data can be used to personalize:

The user's clean videos and video labels for all their objects. Frames can be sampled from these videos in any way and pre-processed/augmented freely. We empirically found that uniformly sampling frames from the clean videos when personalizing yields better performance than other sampling methods, hence all our baselines use this sampling method.

---

In the above snippet, it's written that we can freely augment/preprocess these videos. Given that we are doing some pre-processing of the clean data using a lightweight neural network, my question is: do we need to take into account the MACs of this neural network during this pre-processing phase, in the overall MACs to personalization count?

Many thanks for considering my question.
Sincerely,
Sebastian Cavada

**Comment by danielamassiceti** [comment]
Hi Sebastian

Thanks for your interest in the project. Yes, for fairness, since a neural network is used for the pre-processing, it should be included in the MACs to personalisation count. If the processing involved simpler transformations (e.g. cropping, rotation, adding noise), then I don't think it would be relevant to include MACs.

Best
Daniela
